import styles from './layout.module.scss'
import Head from  'next/head'
import Nav from './Nav'

export default function layout(props){
    return(
        <div className={styles.layout}>
            <Head>
                <title>Crown Clothing || Choose Your Love</title>
                <meta name="description" context="Generated by create next app"></meta>
                <link rel="icon" href="/favicon.svg"/>
            </Head>
            <Nav/>

            <main className={styles.main}>{props.children}</main>
        </div>
    )

}